### ISSUE TITLE
Dragndrop: bad USL display

### ISSUE THREAD

**Issue by Vayel** [IEMLdev/Intlekt-editor#30]
```
{
        "id": "598892fb51bc0232fa6c0eb5",
        "groups": [],
        "default_translations": {
            "en": "process | grammatical \"verbishness\" | bi-polarity | (U:+A:)",
            "fr": "processus | \"verbalité\" grammaticale | bi-polarité | (U:+A:)"
        },
        "ieml": "[([O:])]",
        "translations": {},
        "tags": [],
        "_cls": "USL.Word.Term"
    }
```

Generates an error with the helper of the dnd:

```
Uncaught SyntaxError: Unexpected token v in JSON at position 98
    at JSON.parse (<anonymous>)
    at HTMLTableRowElement.helper (http://localhost:3000/scripts.js:13427:32)
    at t.(anonymous function).(anonymous function)._createHelper (http://localhost:3000/static/js/jquery-ui.min.js:6:29519)
    at t.(anonymous function).(anonymous function)._createHelper (http://localhost:3000/static/js/jquery-ui.min.js:6:4499)
    at t.(anonymous function).(anonymous function)._mouseStart (http://localhost:3000/static/js/jquery-ui.min.js:6:26487)
    at t.(anonymous function).(anonymous function)._mouseStart (http://localhost:3000/static/js/jquery-ui.min.js:6:4499)
    at t.(anonymous function).(anonymous function)._mouseMove (http://localhost:3000/static/js/jquery-ui.min.js:6:23325)
    at t.(anonymous function).(anonymous function)._mouseMove (http://localhost:3000/static/js/jquery-ui.min.js:6:4499)
    at HTMLDocument.n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseMoveDelegate (http://localhost:3000/static/js/jquery-ui.min.js:6:22572)
    at HTMLDocument.dispatch (http://localhost:3000/static/js/jquery-3.2.1.min.js:3:10316)
```

**Comment by Vayel** [comment]
The problem is the quote in the translation.
